version: '3.4'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - helix-db-data:/var/lib/postgresql/data
    # ports:
    #   - '6050:5432'

  redis:
    image: redis:latest
    volumes:
      - helix-redis-data:/data

  server:
    image: helix/helix-server:latest
    build:
      context: ./
      dockerfile: api.Dockerfile
      cache_from:
        - helix/helix-server:latest
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - ./:/code
    ports:
      - '9000:9000'
    depends_on:
      - db
      - redis

  celery:
    image: helix/helix-worker:latest
    restart: 'on-failure'
    build:
      context: ./
      dockerfile: worker.Dockerfile
    env_file:
      - .env
    environment:
      - DEBUG=False
    command: ./deploy/scripts/run_tasks.sh
    volumes:
      - ./:/code

volumes:
  helix-db-data:
  helix-redis-data:
