version: '3.2'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - helix-db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - helix-redis-data:/data

  server:
    image: helix/helix-server:latest
    build:
      context: ./
      cache_from:
        - helix/helix-server:latest
    env_file:
      - .env

    command: bash -c '/code/deploy/scripts/run_dev.sh'
    volumes:
      - ./:/code
    ports:
      - '9000:9000'
    depends_on:
      - db
      - redis

volumes:
  helix-db-data:
  helix-redis-data:
