version: '3.4'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - helix-db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - helix-redis-data:/data

  server:
    image: helix/helix-server:latest
    build:
      context: ./
      target: server
      cache_from:
        - helix/helix-server:latest
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - ./:/code
    ports:
      - '9000:9000'
    depends_on:
      - db
      - redis

  dramatiq:
    image: helix/helix-worker:latest
    restart: 'on-failure'
    build:
      context: ./
      target: dramatiq
    env_file:
      - .env
    command: python manage.py rundramatiq --reload
    volumes:
      - ./:/code

volumes:
  helix-db-data:
  helix-redis-data:
