# Generated by Django 3.2 on 2024-04-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0059_auto_20240326_0824'),
        ('report', '0059_auto_20240327_0937'),
    ]

    operations = [
    ]
