Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
Resources:
  helixs3:
    Metadata:
      'aws:copilot:description': 'An Amazon S3 bucket to store and retrieve objects for helix-s3'
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      BucketName: !Sub '${App}-${Env}-helix-s3'
      PublicAccessBlockConfiguration:
        # NOTE: Make the bucket public
        BlockPublicAcls: false
        BlockPublicPolicy: false

  helixs3BucketPolicy:
    Metadata:
      'aws:copilot:description': 'A bucket policy to deny unencrypted access to the bucket and its contents'
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          # NOTE: Allow all objects read
          - Sid: ReadAny
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
              - !Sub ${ helixs3.Arn}/*
          - Sid: ForceHTTPS
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: 
              - !Sub ${ helixs3.Arn}/*
              - !Sub ${ helixs3.Arn}
            Condition: 
              Bool:
                "aws:SecureTransport": false
      Bucket: !Ref helixs3

  helixs3AccessPolicy:
    Metadata:
      'aws:copilot:description': 'An IAM ManagedPolicy for your service to access the helix-s3 bucket'
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub
        - Grants CRUD access to the S3 bucket ${Bucket}
        - { Bucket: !Ref helixs3 }
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: S3ObjectActions
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:PutObjectACL
              - s3:PutObjectTagging
              - s3:DeleteObject
              - s3:RestoreObject
            Resource: !Sub ${ helixs3.Arn}/*
          - Sid: S3ListAction
            Effect: Allow
            Action: s3:ListBucket
            Resource: !Sub ${ helixs3.Arn}

Outputs:
  # NOTE: making this bucket environment var uniform across stack
  copilotS3BucketName:
    Description: "The name of a user-defined bucket."
    Value: !Ref helixs3
    # NOTE: export the name so it can be used elsewhere in the stack
    Export:
      Name: !Sub ${App}-${Env}-S3BucketName
  helixs3AccessPolicy:
    Description: "The IAM::ManagedPolicy to attach to the task role"
    Value: !Ref helixs3AccessPolicy
