service: htmltopdf
# app and org for use with dashboard.serverless.com
#app: htmltopdf-app
#org: annshress

provider:
  name: aws
  runtime: python3.8
  stage: dev
  profile: ${file(./config.yml):AWS_PROFILE}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - arn:aws:s3:::${file(./config.yml):S3_BUCKET_NAME}
        - arn:aws:s3:::${file(./config.yml):S3_BUCKET_NAME}/*
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        - arn:aws:lambda:*:*:function:htmltopdf*


package:
  include:
    - lambda_function.py
    - event-sample.json
    - success_function.py
    - failure_function.py
    - config.yml

functions:
  generatePdf:
    #module: generate_pdf
    handler: lambda_function.handle
    # todo provisionedConcurrency (fixme, failing with destinations)
    destinations:
      onSuccess: destinationHandler
      onFailure: destinationHandler
    environment:
      S3_BUCKET_NAME: ${file(./config.yml):S3_BUCKET_NAME}
    description: Generates pdf based on the given url and stores into s3
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
      - arn:aws:lambda:us-east-1:209357624314:layer:Wkhtmltox:2
  destinationHandler:
    handler: destination_function.handle
    description: Post handler for pdf generation
    environment:
      # todo in production
      WEBHOOK_URL: 'http://79150673b1c4.ngrok.io/webhooks/generate_pdf'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    useDownloadCache: false
    useStaticCache: false
    dockerizePip: false
    # layers and individual packaging dont go hand-in-hand
    layer: true

resources:
 Resources:
   NewResource:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${file(./config.yml):S3_BUCKET_NAME}
