Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
  DBClusterName:
    Type: String
    Description: The prefix of the db cluster name deployed with django server.
    Default: helixdbcluster
  # The following two are under feature request
  # https://github.com/aws/copilot-cli/issues/1449
  Region:
    Type: String
    Description: The region of the account
    Default: us-east-1
  AccountId:
    Type: String
    Description: The id of the account
    Default: 209357624314

Resources:
  # https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/
  ResourceAccessPolicy:
    Metadata:
      'aws:copilot:description': 'This is for the dramatiq service to access the addons created for django service'
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: 'Grants secret manager access; Grants CRUD access to S3 bucket'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: SMActions
            Effect: Allow
            Action:
              - secretsmanager:GetResourcePolicy
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
              - secretsmanager:ListSecretVersionIds,
              - secretsmanager:ListSecrets
            # NOTE: tried with 'arn:aws:secretsmanager:::secret:*' followed by condition, did not work
            Resource:
              !Sub 'arn:aws:secretsmanager:${Region}:${AccountId}:secret:${DBClusterName}*'
          - Sid: S3ObjectActions
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:PutObjectACL
              - s3:PutObjectTagging
              - s3:DeleteObject
              - s3:RestoreObject
            Resource: !Sub 'arn:aws:s3:::${App}-${Env}-s3-bucket/*'
          - Sid: S3ListAction
            Effect: Allow
            Action: s3:ListBucket
            Resource: !Sub 'arn:aws:s3:::${App}-${Env}-s3-bucket'

Outputs:
  # We also need to output the IAM ManagedPolicy so that Copilot can inject it to our ECS task role.
  DramatiqIAMPolicy:
    Description: "The ManagedPolicy to attach to the task role."
    Value: !Ref ResourceAccessPolicy
