# Generated by Django 3.2 on 2024-05-02 03:20

import apps.crisis.models
import apps.entry.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0098_auto_20240326_0824'),
        ('country', '0018_auto_20240326_0824'),
        ('event', '0001_auto_20240326_0824'),
        ('gidd', '0030_auto_20240114_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiddEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Event Name')),
                ('cause', django_enumfield.db.fields.EnumField(enum=apps.crisis.models.Crisis.CRISIS_TYPE)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_date_accuracy', models.TextField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_date_accuracy', models.TextField(blank=True, null=True)),
                ('glide_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Event Codes'), default=list, size=None)),
                ('event_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Event Codes'), default=list, size=None)),
                ('event_codes_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Event Code Types'), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('violence_name', models.CharField(blank=True, max_length=256, null=True)),
                ('violence_sub_type_name', models.CharField(blank=True, max_length=256, null=True)),
                ('hazard_category_name', models.CharField(blank=True, max_length=256, null=True)),
                ('hazard_sub_category_name', models.CharField(blank=True, max_length=256, null=True)),
                ('hazard_sub_type_name', models.CharField(blank=True, max_length=256, null=True)),
                ('hazard_type_name', models.CharField(blank=True, max_length=256, null=True)),
                ('other_sub_type_name', models.CharField(blank=True, max_length=256, null=True)),
                ('osv_sub_type_name', models.CharField(blank=True, max_length=256, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.event', verbose_name='Event')),
                ('hazard_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.disastercategory', verbose_name='Figure Hazard Category')),
                ('hazard_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.disastersubcategory', verbose_name='Figure Hazard Sub Category')),
                ('hazard_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.disastersubtype', verbose_name='Figure Hazard Sub Type')),
                ('hazard_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.disastertype', verbose_name='Figure Hazard Type')),
                ('osv_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.osvsubtype', verbose_name='Figure OSV sub type')),
                ('other_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.othersubtype', verbose_name='Other sub type')),
                ('violence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.violence', verbose_name='Figure Violence')),
                ('violence_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.violencesubtype', verbose_name='Figure Violence Sub Type')),
            ],
        ),
        migrations.CreateModel(
            name='GiddFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(max_length=5, verbose_name='ISO3')),
                ('country_name', models.CharField(max_length=256, verbose_name='Country name')),
                ('geographical_region', models.CharField(blank=True, max_length=256, null=True, verbose_name='Geographical Region')),
                ('term', django_enumfield.db.fields.EnumField(blank=True, enum=apps.entry.models.Figure.FIGURE_TERMS, null=True)),
                ('locations_coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Geo Locations'), default=list, size=None)),
                ('year', models.IntegerField()),
                ('unit', django_enumfield.db.fields.EnumField(enum=apps.entry.models.Figure.UNIT)),
                ('category', django_enumfield.db.fields.EnumField(blank=True, enum=apps.entry.models.Figure.FIGURE_CATEGORY_TYPES, null=True)),
                ('cause', django_enumfield.db.fields.EnumField(blank=True, enum=apps.crisis.models.Crisis.CRISIS_TYPE, null=True)),
                ('role', django_enumfield.db.fields.EnumField(blank=True, enum=apps.entry.models.Figure.ROLE, null=True)),
                ('total_figures', models.PositiveIntegerField(verbose_name='Total Figures')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_date_accuracy', models.TextField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_date_accuracy', models.TextField(blank=True, null=True)),
                ('stock_date', models.DateField(blank=True, null=True)),
                ('stock_date_accuracy', models.TextField(blank=True, null=True)),
                ('stock_reporting_date', models.DateField(blank=True, null=True)),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Sources'), default=list, size=None)),
                ('sources_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Sources Type'), default=list, size=None)),
                ('publishers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Publishers'), default=list, size=None)),
                ('is_housing_destruction', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Housing Destruction')),
                ('include_idu', models.BooleanField(verbose_name='Include in IDU')),
                ('excerpt_idu', models.TextField(blank=True, null=True, verbose_name='Excerpt for IDU')),
                ('locations_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Location Names'), default=list, size=None)),
                ('locations_accuracy', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Location Accuracy'), default=list, size=None)),
                ('locations_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Location Type'), default=list, size=None)),
                ('displacement_occurred', django_enumfield.db.fields.EnumField(blank=True, enum=apps.entry.models.Figure.DISPLACEMENT_OCCURRED, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gidd_figures', to='country.country', verbose_name='Country')),
                ('figure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='entry.figure')),
                ('gidd_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gidd_figures', to='gidd.giddevent', verbose_name='GIDD Event')),
            ],
        ),
    ]
