# Generated by Django 3.2 on 2024-05-01 11:50

import apps.entry.models
import django.contrib.postgres.fields
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0031_alter_idpssaddestimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='displacement_occurred',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=apps.entry.models.Figure.DISPLACEMENT_OCCURRED), default=list, size=None),
        ),
    ]
