# Generated by Django 3.2 on 2024-05-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0033_giddevent_giddfigure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiddFigure',
        ),
        migrations.DeleteModel(
            name='GiddEvent',
        ),
    ]
