name: Django Test Runner

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  GITHUB_WORKFLOW: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          touch .env
          docker-compose build
      - name: Run Tests
        run: |
          docker-compose run server py.test
